#!/usr/bin/with-contenv sh
echo >&2 "starting Fluent Bit"

exec /opt/fluent-bit/bin/fluent-bit -c /etc/fluent-bit/fluent-bit.conf -path.home /opt/fluent-bit/ -path.config /etc/fluent-bit -path.data /var/fluent-bit -path.logs /var/log/fluent-bit
